"""Topic boundaries for project-based engineering research notes."""
TOPICS = [
    ('agent-runtime-boundaries', 'agentic-platform', 'Designing the handoff between conversation and agent execution', 'What the runtime loader makes explicit, and which decisions belong outside the model.', ['request', 'tradeoffs'], ['runtime', 'tools']),
    ('agent-evaluation-promotion', 'agentic-platform', 'From a failed agent run to a reviewed version change', 'Separating execution evidence, failure diagnosis, and promotion in the Agentic AI Platform.', ['diagnosis', 'recovery', 'authorization'], ['evaluation']),
    ('hermes-streaming-ownership', 'hermes', 'Session ownership and streaming in an AI workspace', 'Why a browser connection, a user session, and a runtime credential need different identities.', ['request-flow', 'streaming'], ['boundary']),
    ('hermes-knowledge-isolation', 'hermes', 'Knowledge fallback without hiding failed document changes', 'The consistency tradeoff between degraded retrieval and failed mutations in Hermes.', ['knowledge-detail', 'release-checks'], ['knowledge', 'versions']),
    ('voc-taxonomy-retrieval', 'voc', 'Grounded inquiry classification begins with a clear taxonomy', 'What retrieval can clarify, and what a classifier must still decide across customer messages.', ['example', 'contract'], ['workflow', 'design']),
    ('voc-evaluation-review', 'voc', 'Evaluating inquiry intelligence beyond aggregate accuracy', 'Class-level mistakes, channel differences, reviewer effort, and duplicate ingestion.', ['evaluation', 'review-cost'], ['problem']),
    ('sales-recovery-decisions', 'sales-recovery', 'Eligibility, priority, and action in sales recovery', 'Why quotation matching and follow-up ranking should remain separate decisions.', ['opportunity', 'decision'], ['workflow']),
    ('sales-recovery-reliability', 'sales-recovery', 'Reliable follow-up and honest measurement of sales recovery', 'Inspecting retries and duplicate actions without confusing activity with commercial impact.', ['retries', 'measurement'], ['choices']),
    ('data-model-grain', 'data-platform', 'A shared data model starts with the meaning of one row', 'Grain, reusable transformations, and the logic behind Power BI totals.', ['grain', 'layers'], ['workflow']),
    ('data-quality-reconciliation', 'data-platform', 'A successful pipeline is not proof of correct reporting', 'Late corrections, repeatable intervals, and checks at the business-consumer boundary.', ['incremental', 'quality'], ['contribution']),
    ('vision-recognition-similarity', 'visual-recognition', 'Detection, recognition, and similarity search on retail shelves', 'Why locating a package and identifying its SKU need separate evidence.', ['recognition-detail', 'similarity'], ['pipeline']),
    ('vision-end-to-end-evaluation', 'visual-recognition', 'Evaluate the shelf audit, not only the vision model', 'Separating localization, identity, serving behavior, and the human audit outcome.', ['evaluation-detail', 'serving'], ['results']),
]

BASIS = {
    'agentic-platform': 'This note draws on the local runtime loader and the platform architecture notes. The loader prepares flow and team data and exposes routing and completion tools. Evaluation and promotion are separate design responsibilities. Local source inspection does not establish live end-to-end reliability.',
    'hermes': 'This note draws on the documented Hermes prototype described in my project materials: a Next.js portal, FastAPI backend, session ownership, runtime streaming, and optional knowledge integration. The default local setup uses mock mode. No new live integration or security experiment was run for this article.',
    'voc': 'This note starts from my VOC Inquiry Intelligence work: preparation of emails and calls, a 108-type inquiry taxonomy, retrieval-assisted analysis, human review, and downstream reporting. The public project materials are the evidence for those responsibilities; confidential production code and measurements are not reproduced.',
    'sales-recovery': 'This note starts from my Sales Recovery workflow, which connects quotation and order information, business rules, scheduled monitoring, and Power Automate follow-up. Internal matching rules and commercial outcomes are not disclosed. The examples below explain design risks rather than report internal incidents.',
    'data-platform': 'This note starts from my work with Airflow, dbt, SQL, Docker, and Power BI to provide shared models for reporting and automation. Internal schemas, loading policies, and warehouse details are outside the public record. Modeling and test examples below are illustrative.',
    'visual-recognition': 'This note starts from my retail vision work: YOLO detection, CNN and ViT recognition, similarity search, API serving, and shelf analytics. Public materials report 750+ SKU classes and an audit-time change from 45 to 15 minutes. Training details and evaluation conditions are not public.',
}
